### ISSUE TITLE
Goal 1: Single sign-on

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/zk-groups#1]
**Tasks**:

- [x] Define the design
- [x] Create `login` page
- [x] Create `sign-in` component
- [x] Twitter Passport strategy
- [x] Github Passport strategy
- [x] #12
- [x] Create `sign-in` API
- [x] Manage sessions
- [x] #13

**Resources**:

* [Nx](https://nx.dev/)
* [React](https://reactjs.org/) ([Github](https://github.com/reactjs))
* [Chakra UI](https://chakra-ui.com/) ([Github](https://github.com/chakra-ui))
* [Nest.JS](https://docs.nestjs.com) ([Github](https://github.com/nestjs/nest))
* [Passport](https://www.passportjs.org/) ([Github](https://github.com/jaredhanson/passport))
* [Implementing Passport strategies with Nest.JS](https://docs.nestjs.com/security/authentication#implementing-passport-strategies) ([Github](https://github.com/nestjs/passport))
* [MongoDB for Nest.JS](https://docs.nestjs.com/techniques/mongodb)
