### ISSUE TITLE
Goal 2: Dashboard

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/zk-groups#2]
**Tasks**:

- [x] Define the design
- [x] Create `dashboard` page
- [x] Create `dashboard` components
- [x] Create `dashboard`APIs (`create-group`, `add-member`, `remove-member`)
- [x] Create MongoDB models

**Resources**:

* [Nx](https://nx.dev/)
* [React](https://reactjs.org/) ([Github](https://github.com/reactjs))
* [Chakra UI](https://chakra-ui.com/) ([Github](https://github.com/chakra-ui))
* [Nest.JS](https://docs.nestjs.com) ([Github](https://github.com/nestjs/nest))
* [MongoDB for Nest.JS](https://docs.nestjs.com/techniques/mongodb)
