### ISSUE TITLE
M2 - Goal 1: Reputation groups

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/zk-groups#23]
**Description**:

Users will be able to authenticate with Twitter, Reddit, and Github so that ZK-Groups can calculate their Web2 reputation based on parameters and thresholds decided by the admin of the group.

**Tasks**:

- [ ] Allow admins to create reputation groups in the dashboard
- [ ] API to create reputation groups
- [ ] API to add members to reputation groups
- [ ] Ensure Web2 accounts can only be linked to 1 Semaphore identity at a time
