### ISSUE TITLE
Goal 3: APIs

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/zk-groups#4]
**Tasks**:

- [x] Create an API to generate Merkle proofs
- [x] Create an API to get group data
- [x] Create a data structure for groups

**Resources**:

* [Nest.JS](https://docs.nestjs.com) ([Github](https://github.com/nestjs/nest))
* [MongoDB for Nest.JS](https://docs.nestjs.com/techniques/mongodb)
